on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: mradamh/project-zomboid-dedicated-server:latest

      - name: Update description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: mradamh/project-zomboid-dedicated-server